# Config Test for GitHub Hosting...
title: mrblaschke-jekyll
email: jekyll@mrblaschke.de
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# baseurl: "/_deploy" # the subpath of your site, e.g. /blog
baseurl: "/" # the subpath of your site, e.g. /blog
# url: "https://raw.mrblaschke.de" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://mrblaschke.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hans_wurst09
github_username:  MrBlaschke

# Build settings
markdown: kramdown


highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
#  poetry:
#    output: true
#    permalink: /poetry/:path/




#theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
theme: jekyll-theme-cayman